/*! CWS Accessibility - v4.4.1 - 2021
* Author: U Arun Kumar, Symphony Talent - https://www.symphonytalent.com/
* Using this file we can add/modify accessibility settings on the go using simple javascript and/or jQuery code.
* Copyright 2021 Symphony Talent and their employees; Licensed Symphony Talent */
(function(){function labelTabs(){var $=jQuery;$('.top_tab, .sidebar_tab').each(function(containerIndex){var $container=$(this);var baseId=$container.attr('id')||('cws-tab-container-'+(containerIndex+1));$container.attr('id',baseId);$container.find('.tab_titles .tab').each(function(tabIndex){var $tab=$(this);var tabId=$tab.attr('id')||(baseId+'-tab-'+(tabIndex+1));$tab.attr('id',tabId);var $panel=$container.find('.tab_content').eq(tabIndex);if($panel.length){$panel.attr('id',$panel.attr('id')||(baseId+'-panel-'+(tabIndex+1))).attr('aria-labelledby',tabId);}});});}
function maintainTabSelectionState(){var $=jQuery;var containerSelector='.top_tab, .sidebar_tab';var tabSelector='.tab_titles .tab, .fullsize-tab';var activeClass='active_tab';function syncContainer($container){$container.find(tabSelector).each(function(){$(this).attr('aria-selected',$(this).hasClass(activeClass)?'true':'false');});}
function deferSync($container){if($container&&$container.length){(window.requestAnimationFrame||function(cb){return setTimeout(cb,0);})(function(){syncContainer($container);});}}
$(containerSelector).each(function(){var $container=$(this);var eventsNamespace='.cwsTabSelection';syncContainer($container);$container.off(eventsNamespace);$container.on('focusin'+eventsNamespace,tabSelector,function(){var $focused=$(this);if(!$focused.hasClass(activeClass)){$focused.attr('aria-selected','false');}
deferSync($container);});$container.on('keydown'+eventsNamespace,tabSelector,function(event){var key=event.which;if(key===13||key===32||key===37||key===38||key===39||key===40){deferSync($container);}});$container.on('click'+eventsNamespace,tabSelector,function(){deferSync($container);});$container.on('tabsync'+eventsNamespace,function(){deferSync($container);});});}
jQuery(document).ready(function(){var $=jQuery;if(window.location.href.indexOf("/profile/preferences")&&typeof CWS!=='undefined'){$(document).on('mouseenter','.ui-select-container',function(){$('span.ui-select-match span.close').attr('role','button');$('span.ui-select-match span.close').attr('tabindex',0);$('.ui-select-choices').attr('role','listbox').attr('aria-label',CWS._('Select an option'));$('span.ui-select-match span.ui-select-match-item').each(function(){var selectedOption=$(this).children().last().text();$(this).find('span.close').attr('aria-label',CWS._('Remove')+" "+selectedOption);$(this).find('span[uis-transclude-append]').attr('aria-hidden','true');});});$(document).on('keyup','.ui-select-container',function(e){if(e.keyCode==13||e.keyCode==9){$('span.ui-select-match span.close').attr('role','button');$('span.ui-select-match span.close').attr('tabindex',0);$('.ui-select-choices').attr('role','listbox').attr('aria-label',CWS._('Select an option'));$('span.ui-select-match span.ui-select-match-item').each(function(){var selectedOption=$(this).children().last().text();$(this).find('span.close').attr('aria-label',CWS._('Remove')+" "+selectedOption);});}
$('.ui-select-multiple').each(function(){var firstOption=$(this).find('.ui-select-choices-row:first').attr('id');var firstOptionActive=$(this).find('.ui-select-choices-row:first').hasClass('active');if(firstOption!==undefined&&firstOption!==null&&firstOptionActive===true){$(this).find('.ui-select-search').attr('aria-activedescendant',firstOption);}});});}
if($('.search-results-table').length>0&&$('.search-results-table').attr("role")=="table"){$('.widget-jobsearch-results').not('.table_tile').find('.search-results-table').find('#widget-jobsearch-results-list').attr("role","presentation");}
window.onpopstate=function(){if(window.location.href.indexOf('/profile/thank-you/')!==-1){document.title="Thank You";}else if(window.location.href.indexOf('/profile/join/')!==-1){document.title="Join our Talent Community";}
$('#aria-live span').hide();$('#aria-live').append('<span>'+document.title+' Page </span>');};});jQuery(window).on('load',function(){var $=jQuery;if(window.location.href.indexOf("/profile/preferences")&&typeof CWS!=='undefined'){$('.ui-select-choices').attr('role','listbox');$('.ui-select-choices').find('.ui-select-choices-group').attr('role','presentation');$('.ui-select-choices').find('.ui-select-choices-row').attr('role','option');}
labelTabs();maintainTabSelectionState();});})()