!function(e,n){e.wp=e.wp||{},e.wp.mediaelement=new function(){var t={};return{initialize:function(){var e=[];(t="undefined"!=typeof _wpmejsSettings?n.extend(!0,{},_wpmejsSettings):t).classPrefix="mejs-",t.success=t.success||function(e){var t,n;e.rendererName&&-1!==e.rendererName.indexOf("flash")&&(t=e.attributes.autoplay&&"false"!==e.attributes.autoplay,n=e.attributes.loop&&"false"!==e.attributes.loop,t&&e.addEventListener("canplay",function(){e.play()},!1),n)&&e.addEventListener("ended",function(){e.play()},!1)},t.customError=function(e,t){if(-1!==e.rendererName.indexOf("flash")||-1!==e.rendererName.indexOf("flv"))return'<a href="'+t.src+'">'+mejsL10n.strings["mejs.download-file"]+"</a>"},void 0!==t.videoShortcodeLibrary&&"mediaelement"!==t.videoShortcodeLibrary||e.push(".wp-video-shortcode"),void 0!==t.audioShortcodeLibrary&&"mediaelement"!==t.audioShortcodeLibrary||e.push(".wp-audio-shortcode"),e.length&&n(e.join(", ")).not(".mejs-container").filter(function(){return!n(this).parent().hasClass("mejs-mediaelement")}).mediaelementplayer(t)}}},n(e.wp.mediaelement.initialize)}(window,jQuery);
;read_language_cookie=function(){var cookie=null;var cookie_value=window.location.href.split('/')[3].trim();if(cookie_value){write_language_cookie(cookie_value);}
cookie=CWS.cookies.getItem('cws_current_language');return cookie;};write_language_cookie=function(cookie_value){var expDate=new Date(new Date().getTime()+1000*60*60*24*30);CWS.cookies.setItem('cws_current_language',cookie_value,expDate.toGMTString(),'/',window.location.host);};jQuery(document).ready(function(){var cookie=read_language_cookie();var showVal='Show',hideVal='Hide',skipNavTxt='Skip to main content';if(cookie!=null){if(cookie.toLowerCase()=='fr-ca'){showVal='Lire';hideVal='Cacher';skipNavTxt='Passer au contenu principal';}}
jQuery('.col-controls,.ascending,.descending').removeAttr("style");var tab_hash_value=window.location.hash;if(/^#tab-id-[a-zA-Z0-9_-]+$/.test(tab_hash_value)){$(tab_hash_value).click();}});jQuery(function($){if($('h1').first().length>0){if($('h1').first().attr('id')==undefined){$('h1').first().attr('id','pageHeaderTop');}
$('h1').first().attr('tabindex','-1');$('#wrap_all').prepend('<div class="check-style-enabled"></div><div id="skipnav"><a href="#'+$('h1').first().attr('id')+'" target="_self">'+CWS._('Skip to main content')+'</a></div>');}else{$('#wrap_all').prepend('<div class="check-style-enabled"></div><div id="skipnav"><a href="#main" target="_self">'+CWS._('Skip to main content')+'</a></div>');}
$('body').append('<span class="offscreen" aria-hidden="true" id="level2">level 2</span>');$('#mobile-advanced ul li').attr('aria-describedby','level2');$('.menu-item-language img.iclflag').attr({'alt':'','title':''});$('#scroll-top-link').removeAttr('aria-hidden');$('a#advanced_menu_toggle,a#advanced_menu_hide').removeAttr('aria-hidden').attr('role','button');$('a#job-alert,a#cws-adv-search-btn,#gtm-jobdetail-apply a,#gtm-jobdetail-mind a,#gtm-jobdetail-cart a').attr('role','button');$('#mobile-advanced').attr('role','menu');$('.hodes-menu').attr('role','menubar');$('.hodes-menu').find('span.avia-bullet,span.avia-menu-fx,span.avia-arrow-wrap,span.dropdown_available').attr('aria-hidden','true');$('.hodes-menu,#mobile-advanced').find('ul').attr('role','menu');$('.hodes-menu,#mobile-advanced').find('li').attr('role','presentation');$('.hodes-menu,#mobile-advanced').find('.menu-item a').attr('role','menuitem');$('.hodes-menu').find('.dropdown_ul_available > a').attr({'aria-haspopup':'true','aria-expanded':'false'});$('.hodes-menu').find('.menu-item-language:first > a').attr({'aria-haspopup':'true','aria-expanded':'false'});$('.hodes-menu li a').on('keydown',keyboardHandler);$('#mobile-advanced li a').on('keydown',mobileHandler);var mobile_menu_active=false;var tab_hash_value=window.location.hash;if(/^#tab-id-[a-zA-Z0-9_-]+$/.test(tab_hash_value)){$(tab_hash_value).click();}
function mobileHandler(keyVent){var target=keyVent.target;var which=keyVent.which;mobile_menu_active=true;$('#mobile-advanced').addClass('menu');if(which===9&&keyVent.shiftKey){if(!isTopLevel(target)&&isFirstDropItem(target)){keyVent.preventDefault();var topA=closeDropdown(target);setTimeout(function(){topA.focus();},0);}}
else if(which===9){if(hasDropdown(target)){openDropdown(target);}
else if(isLastDropItem(target)){topItem=closeDropdown(target);nextLi=$(topItem.parentNode).next()[0];if(typeof(nextLi)!=="undefined"){if(nextLi!==null){keyVent.preventDefault();var nextAnchor=$('a',nextLi)[0];nextAnchor.focus();}}}}}
function keyboardHandler(keyVent){var target=keyVent.target;var which=keyVent.which;mobile_menu_active=false;if(which===39){if(isTopLevel(target)){var nextTopItem=adjacentTopLevelItem(target,'next');if(nextTopItem){keyVent.preventDefault();nextTopItem.focus();}}else if(!isTopLevel(target)&&($(target.parentNode).hasClass('dropdown_ul_available')||$(target.parentNode).hasClass('menu-item-has-children'))){openDropdown(target);}else{var nextDropletItem=adjacentDropdownItem(target,'next');if(nextDropletItem){keyVent.preventDefault();nextDropletItem.focus();}}}else if(which===37){if(isTopLevel(target)){var prevTopItem=adjacentTopLevelItem(target,'prev');if(prevTopItem){keyVent.preventDefault();prevTopItem.focus();}}else{var prevDropItem=adjacentDropdownItem(target,'prev');if(prevDropItem){keyVent.preventDefault();prevDropItem.focus();}}}else if(which===40){if(isTopLevel(target)&&hasDropdown(target)){keyVent.preventDefault();openDropdown(target);}else{var nextDropItem=adjacentDropdownItem(target,'next');keyVent.preventDefault();if(nextDropItem){keyVent.preventDefault();nextDropItem.focus();}}}else if(which===38){if(!isTopLevel(target)){if(isFirstDropItem(target)){keyVent.preventDefault();var top=closeDropdown(target);setTimeout(function(){top.focus();},0);}else{var prevDropAnchor=adjacentDropdownItem(target,'prev');if(prevDropAnchor){keyVent.preventDefault();prevDropAnchor.focus();}}}}else if(which===27){if(!isTopLevel(target)){var topper=closeDropdown(target);setTimeout(function(){topper.focus();},0);}}else if(which===9&&keyVent.shiftKey){if(!isTopLevel(target)&&isFirstDropItem(target)){keyVent.preventDefault();var topA=closeDropdown(target);setTimeout(function(){topA.focus();},0);}}else if(which===9){if(!isTopLevel(target)){var topItem=null;var nextLi=null;if(isLastDropItem(target)){topItem=closeDropdown(target);nextLi=$(topItem.parentNode).next()[0];if(typeof(nextLi)!=="undefined"){if(nextLi!==null){keyVent.preventDefault();var nextAnchor=$('a',nextLi)[0];nextAnchor.focus();}}}else if(hasDropdown(target)&&isFirstHasDropDownLastDropItem(target)){topItem=closeDropdown(target);nextLi=$(topItem.parentNode).next()[0];if(typeof(nextLi)!=="undefined"){if(nextLi!==null){keyVent.preventDefault();var nextAnchor=$('a',nextLi)[0];nextAnchor.focus();}}}else{var nextDropletItem=adjacentDropdownItem(target,'next');if(nextDropletItem){keyVent.preventDefault();nextDropletItem.focus();}}}else if(isTopLevel(target)){var nextTopItem=adjacentTopLevelItem(target,'next');if(nextTopItem){if(hasDropdown(target)){var droplet=$(target).next('.sub-menu');closeDropdown(droplet);keyVent.preventDefault();nextTopItem.focus();}}}}else if(which===13||which===32){if(which==32){keyVent.preventDefault();}
if(isTopLevel(target)&&($(target.parentNode).hasClass('dropdown_ul_available')||$(target.parentNode).hasClass('menu-item-has-children'))){openDropdown(target);}}}
function isTopLevel(item){return $(item).is('.menu > li > a');}
function hasDropdown(item){return($(item.parentNode).hasClass('menu-item-has-children')||$(item.parentNode).hasClass('menu-item-language-current'));}
function isFirstDropItem(item){var drop=$(item).closest('.sub-menu')[0];var firstInDrop=$('li a',drop)[0];return firstInDrop===item;}
function isLastDropItem(item){var drop=$(item).closest('.sub-menu')[0];var lastInDrop=$('li a',drop).last()[0];return lastInDrop===item;}
function isFirstHasDropDownLastDropItem(item){var drop=$(item).parent().closest('.sub-menu')[0];var lastInDrop=$(drop).children().children().not('ul').last()[0];return lastInDrop===item;}
function adjacentTopLevelItem(item,dir){var li=item.parentNode;var adjacentLi=(dir==='next')?$(li).next()[0]:$(li).prev()[0];var adjacentItem=adjacentLi&&$('a',adjacentLi)[0];return adjacentItem;}
function adjacentDropdownItem(item,dir){var adjacentDropItem;var li=item.parentNode;var adjacentSameCol=(dir==='next')?$(li).next()[0]:$(li).prev()[0];if(adjacentSameCol){adjacentDropItem=$('a',adjacentSameCol)[0];}else{var col=$(li).closest('.sub-menu')[0];var adjacentCol=(dir==='next')?$(col).next()[0]:$(col).prev()[0];if(adjacentCol){var adjacentItem=(dir==='next')?$('li a',adjacentCol)[0]:$('li a',adjacentCol).last()[0];if(adjacentItem){adjacentDropItem=adjacentItem;}}}
return adjacentDropItem;}
function openDropdown(item){$(item.parentNode).addClass('active');$(item).attr('aria-expanded','true');var droplet=$(item).next('.sub-menu');if(!mobile_menu_active){$(droplet).stop().css({visibility:'visible',display:'block'}).animate({opacity:1});}
setTimeout(function(){$('a',droplet)[0].focus();},100);}
function closeDropdown(item){var droplet=$(item).closest('.sub-menu')[0];do{var topLevelItem=$(droplet).prev()[0];$(topLevelItem.parentNode).removeClass('active');$(topLevelItem).attr('aria-expanded','false');if(!mobile_menu_active){$(droplet).slideUp(100);$(droplet).stop().css({visibility:'hidden'}).animate({opacity:0});}
if((typeof($(topLevelItem.parentNode).next()[0])!=='undefined')||mobile_menu_active){break;}else{droplet=$(topLevelItem).closest('.sub-menu')[0];if(typeof droplet==='undefined'){break;}}}while(1);return topLevelItem;}
function hideShow(id){this.$id=$('#'+id);this.$region=$('#'+this.$id.attr('aria-controls'));this.keys={enter:13,space:32};this.toggleSpeed=100;this.bindHandlers();}
hideShow.prototype.bindHandlers=function(){var thisObj=this;this.$id.click(function(e){thisObj.toggleRegion();e.stopPropagation();return false;});}
hideShow.prototype.toggleRegion=function(){var thisObj=this;this.$region.slideToggle(this.toggleSpeed,function(){if(thisObj.$id.attr('aria-expanded')=='true'){thisObj.$id.attr('aria-label',CWS._('Show Video Transcript'));thisObj.$id.attr('aria-expanded','false');}else{thisObj.$id.attr('aria-label',CWS._('Hide Video Transcript'));thisObj.$id.attr('aria-expanded','true');$(this).focus();}});}
if($('#open-transcript-btn').length){var hs1=new hideShow('open-transcript-btn');}
$('#avia2-menu li.menu-item-language-current ').hover(function(){$('#avia2-menu').find('li.menu-item-language:first > a').attr('aria-expanded','true');},function(){$('#avia2-menu').find('li.menu-item-language:first > a').attr('aria-expanded','false');});$('.lang-text a').each(function(){if($(this).attr('href')=="/en/"){$(this).attr('aria-label','US');}
if($(this).attr('href')=="/en-CA/"){$(this).attr('aria-label','Canada English');}
if($(this).attr('href')=="/fr-CA/"){$(this).attr('aria-label','Canada French');}});$(".menu-item-language a").each(function(){if($(this).attr('href')=='#'){var url=window.location.href;}else{var url=$(this).attr('href');}
if(url.indexOf("/en/")!=-1){$(this).attr('aria-label','US');}
if(url.indexOf("/en-CA/")!=-1){$(this).attr('aria-label','Canada English');}
if(url.indexOf("/fr-CA/")!=-1){$(this).attr('aria-label','Canada French');}});if(typeof(_XC_CONFIG)!=='undefined'){$(".xcc-sign-in,.xcc-sign-in-submenu .sign-in-link,.xcc-sign-in-submenu .create-profile-link,.xcc-sign-in-submenu .account-link,.xcc-sign-in-submenu .xcc-log-out").focus(function(){$(".menu-dropdown .xcc-sign-in-submenu").css("transform","scaleY(1)");$('.xcc-sign-in-submenu').show();$(".xcc-sign-in").attr('aria-expanded','true');});$(".create-profile-link").focusout(function(){$(".menu-dropdown .xcc-sign-in-submenu").css("transform","scaleY(0)");$(".xcc-sign-in").attr('aria-expanded','false');});$(".xcc-log-out").focusout(function(){$(".menu-dropdown .xcc-sign-in-submenu").css("transform","scaleY(0)");$(".xcc-sign-in").attr('aria-expanded','false');});var xcc_view_loaded_modifications=function(){var first_h1=$('h1').first();if(first_h1.length>0){if(first_h1.attr('id')===undefined){first_h1.attr('id','pageHeaderTop');}
first_h1.attr('tabindex','-1');var hrefValue=location.pathname+location.search+'#'+first_h1.attr('id');var skipNav=document.getElementById('skipnav');var skipLink=document.createElement('a');skipLink.setAttribute('href',hrefValue);skipLink.setAttribute('target','_self');skipLink.textContent=CWS._('Skip to main content');if(skipNav){skipNav.innerHTML='';skipNav.appendChild(skipLink);}}};if(typeof(XCLOUD)!=='undefined'){if(typeof(XCLOUD.apply_filter)==='function'){XCLOUD.add_filter('cws_adjust_elements_after_view_loaded',xcc_view_loaded_modifications);}}}});
;/*! This file is auto-generated */
window.addComment=function(v){var I,C,h,E=v.document,b={commentReplyClass:"comment-reply-link",commentReplyTitleId:"reply-title",cancelReplyId:"cancel-comment-reply-link",commentFormId:"commentform",temporaryFormId:"wp-temp-form-div",parentIdFieldId:"comment_parent",postIdFieldId:"comment_post_ID"},e=v.MutationObserver||v.WebKitMutationObserver||v.MozMutationObserver,r="querySelector"in E&&"addEventListener"in v,n=!!E.documentElement.dataset;function t(){d(),e&&new e(o).observe(E.body,{childList:!0,subtree:!0})}function d(e){if(r&&(I=g(b.cancelReplyId),C=g(b.commentFormId),I)){I.addEventListener("touchstart",l),I.addEventListener("click",l);function t(e){if((e.metaKey||e.ctrlKey)&&13===e.keyCode&&"a"!==E.activeElement.tagName.toLowerCase())return C.removeEventListener("keydown",t),e.preventDefault(),C.submit.click(),!1}C&&C.addEventListener("keydown",t);for(var n,d=function(e){var t=b.commentReplyClass;e&&e.childNodes||(e=E);e=E.getElementsByClassName?e.getElementsByClassName(t):e.querySelectorAll("."+t);return e}(e),o=0,i=d.length;o<i;o++)(n=d[o]).addEventListener("touchstart",a),n.addEventListener("click",a)}}function l(e){var t,n,d=g(b.temporaryFormId);d&&h&&(g(b.parentIdFieldId).value="0",t=d.textContent,d.parentNode.replaceChild(h,d),this.style.display="none",n=(d=(d=g(b.commentReplyTitleId))&&d.firstChild)&&d.nextSibling,d&&d.nodeType===Node.TEXT_NODE&&t&&(n&&"A"===n.nodeName&&n.id!==b.cancelReplyId&&(n.style.display=""),d.textContent=t),e.preventDefault())}function a(e){var t=g(b.commentReplyTitleId),t=t&&t.firstChild.textContent,n=this,d=m(n,"belowelement"),o=m(n,"commentid"),i=m(n,"respondelement"),r=m(n,"postid"),n=m(n,"replyto")||t;d&&o&&i&&r&&!1===v.addComment.moveForm(d,o,i,r,n)&&e.preventDefault()}function o(e){for(var t=e.length;t--;)if(e[t].addedNodes.length)return void d()}function m(e,t){return n?e.dataset[t]:e.getAttribute("data-"+t)}function g(e){return E.getElementById(e)}return r&&"loading"!==E.readyState?t():r&&v.addEventListener("DOMContentLoaded",t,!1),{init:d,moveForm:function(e,t,n,d,o){var i,r,l,a,m,c,s,e=g(e),n=(h=g(n),g(b.parentIdFieldId)),y=g(b.postIdFieldId),p=g(b.commentReplyTitleId),u=(p=p&&p.firstChild)&&p.nextSibling;if(e&&h&&n){void 0===o&&(o=p&&p.textContent),a=h,m=b.temporaryFormId,c=g(m),s=(s=g(b.commentReplyTitleId))?s.firstChild.textContent:"",c||((c=E.createElement("div")).id=m,c.style.display="none",c.textContent=s,a.parentNode.insertBefore(c,a)),d&&y&&(y.value=d),n.value=t,I.style.display="",e.parentNode.insertBefore(h,e.nextSibling),p&&p.nodeType===Node.TEXT_NODE&&(u&&"A"===u.nodeName&&u.id!==b.cancelReplyId&&(u.style.display="none"),p.textContent=o),I.onclick=function(){return!1};try{for(var f=0;f<C.elements.length;f++)if(i=C.elements[f],r=!1,"getComputedStyle"in v?l=v.getComputedStyle(i):E.documentElement.currentStyle&&(l=i.currentStyle),(i.offsetWidth<=0&&i.offsetHeight<=0||"hidden"===l.visibility)&&(r=!0),"hidden"!==i.type&&!i.disabled&&!r){i.focus();break}}catch(e){}return!1}}}}(window);