var XCLOUD=XCLOUD||{};var XCLOUDInitiLoad=true;var shortcode_settings_init={};function checkForRedirect(){window.location.replace('/'+(_XC_CONFIG.lang?_XC_CONFIG.lang+'/':'')+'profile/login/');}
XCLOUD.cookies={getItem:function(sKey){if(!sKey){return null;}
return decodeURIComponent(document.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(sKey).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"))||null;},setItem:function(sKey,sValue,vEnd,sPath,sDomain,bSecure){if(!sKey||/^(?:expires|max\-age|path|domain|secure)$/i.test(sKey)){return false;}
var sExpires="";if(vEnd){switch(vEnd.constructor){case Number:sExpires=vEnd===Infinity?"; expires=Fri, 31 Dec 9999 23:59:59 GMT":"; max-age="+vEnd;break;case String:sExpires="; expires="+vEnd;break;case Date:sExpires="; expires="+vEnd.toUTCString();break;}}
document.cookie=encodeURIComponent(sKey)+"="+encodeURIComponent(sValue)+sExpires+(sDomain?"; domain="+sDomain:"")+(sPath?"; path="+sPath:"")+(bSecure?"; secure":"");return true;},removeItem:function(sKey,sPath,sDomain){if(!this.hasItem(sKey)){return false;}
document.cookie=encodeURIComponent(sKey)+"=; expires=Thu, 01 Jan 1970 00:00:00 GMT"+(sDomain?"; domain="+sDomain:"")+(sPath?"; path="+sPath:"");return true;},hasItem:function(sKey){if(!sKey){return false;}
return(new RegExp("(?:^|;\\s*)"+encodeURIComponent(sKey).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=")).test(document.cookie);},keys:function(){var aKeys=document.cookie.replace(/((?:^|\s*;)[^\=]+)(?=;|$)|^\s*|\s*(?:\=[^;]*)?(?:\1|$)/g,"").split(/\s*(?:\=[^;]*)?;\s*/);for(var nLen=aKeys.length,nIdx=0;nIdx<nLen;nIdx++){aKeys[nIdx]=decodeURIComponent(aKeys[nIdx]);}
return aKeys;}};XCLOUD.codeCounter=0;XCLOUD.authToken='';XCLOUD.local=(function($){var maxSessionStorageTime=30*60*1000;var service={get:get,set:set,supports:supports,remove:remove,clear:clear};return service;function get(name,session){if(!supports()){return null;}
name=_XC_CONFIG.org+'.'+name;var item=window.localStorage.getItem(name);if(item===undefined||item===null){return null;}else{var jsonItem=JSON.parse(item);var now=new Date().getTime();var then=parseInt(jsonItem.date);}
if(now-then>=maxSessionStorageTime){window.localStorage.removeItem(name);return null;}else{return JSON.parse(jsonItem.data);}}
function set(name,data){try{if(!supports()){return;}
name=_XC_CONFIG.org+'.'+name;var storageItem=new StorageItem(data);window.localStorage.setItem(name,JSON.stringify(storageItem));}
catch(reason){if(console&&console.error){console.error(reason)}}}
function supports(){try{var hasStorage=('localStorage'in window);return hasStorage;}catch(reason){if(console&&console.warn){console.warn('localStorage not supported');}
return false;}}
function remove(name,session){if(!supports()){return;}
if(session){window.sessionStorage.removeItem(name);return;}
window.localStorage.removeItem(name);}
function clear(session){if(!supports()){return;}
if(session){window.sessionStorage.clear();return;}
window.localStorage.clear();}
function StorageItem(data){this.date=''+new Date().getTime();this.data=data;}})(jQuery);XCLOUD.user=(function($){var user=XCLOUD.local.get('candidate');function logged_in(){return user!==null;}
function get(key){if(!logged_in()){return'';}
if(key in user){return user[key];}
return'';}})(jQuery);XCLOUD.personalize=(function($){var xcc=null;var prevFirstName=null;var prevDataIf=null;function get_candidate(){var user=XCLOUD.local.get('candidate');if(user===null){user=XCLOUD.cookies.getItem('xcc');}
if(user!==null&&typeof user==='string'){user=JSON.parse(user);}
return user;}
xcc=get_candidate();var parse_string=function(str){var pattern=/\{\{(.+?)\}\}/g;str=str.replace(pattern,function(match,offset,string){match=match.replace('{{','').replace('}}','');var res=getter(match);res=encodeURIComponent(res);res=res.replace(/%20/g," ");return res;});return str;};var getter=function(key){var xcc=get_candidate();return xcc&&xcc.hasOwnProperty(key)?xcc[key]:'';};return{init:function(params){_XC_CONFIG=XCLOUD.apply_filter('xcc_config',_XC_CONFIG);$('.xcc-sign-in-submenu').remove();$(this).removeClass('out in');$(document.body).click(function(e){if($('.menu-dropdown .xcc-sign-in-submenu')!==null)
$('.xcc-sign-in-submenu').hide();});$('.xcc-sign-in').each(function(){if(($('.xcc-sign-in').closest('nav.main_menu')).length!==0){var parent_el=$(this).parent().parent().parent();}
else{var parent_el=$(this).parent().parent();}
if(parent_el.is('a')){var menu_html=parent_el.html();parent_el.replaceWith('<span>'+menu_html+'</span>');}});xcc=get_candidate();if(xcc===null||xcc.isLocked===true){$('.xcc-logged-out').show();$('.menu-inline .xcc-sign-in').hide();$('.xcc-sign-in').each(function(){if(typeof shortcode_settings_init==="undefined"||shortcode_settings_init==={}){shortcode_settings_init=$(this).data();}
var shortcode_settings=shortcode_settings_init;var submenu='<div class="load-app xcc-sign-in-submenu display-none-mobile" id="sign-in-submenu" aria-hidden="true" ng-controller="signInMenuController">';submenu+='<div id="scriptInjector"></div>';if(_XC_CONFIG.login_modal.disabled===false){_XC_CONFIG.signInHTML='<a class="sign-in-link pointer" href="javascript:angular.element(\'.xcc-sign-in-submenu\').scope().openSignInModal();" ng-click="openSignInModal($event)">'+XCLOUD.i18n(shortcode_settings.login||'Already have a profile?','labels')+'</a>';submenu+=_XC_CONFIG.signInHTML;}
else{_XC_CONFIG.signInHTML='<a class="sign-in-link pointer" onclick="checkForRedirect()">'+XCLOUD.i18n(shortcode_settings.login||'Already have a profile?','labels')+'</a>';submenu+=_XC_CONFIG.signInHTML;}
if(_XC_CONFIG.lead_capture_as_modal=='true'){var applyPage=window.location.pathname;applyPage=applyPage.toLowerCase();if(applyPage.indexOf('/apply/')>-1){submenu+='<a class="create-profile-link" href="/'+(_XC_CONFIG.lang?_XC_CONFIG.lang+'/':'')+'profile/join/">'+XCLOUD.i18n(shortcode_settings.createprofile||'Sign In','labels')+'</a>';}else
{submenu+='<a class="create-profile-link" href="javascript:angular.element(\'.xcc-sign-in-submenu\').scope().openLeadCapture();" ng-click="openLeadCapture($event)">'+XCLOUD.i18n(shortcode_settings.createprofile||'Sign In','labels')+'</a>';}}
else{submenu+='<a class="create-profile-link" href="/'+(_XC_CONFIG.lang?_XC_CONFIG.lang+'/':'')+'profile/join/">'+XCLOUD.i18n(shortcode_settings.createprofile||'Sign In','labels')+'</a>';}
submenu+='</div>';$(this).parent().addClass('xcc-sign-in-parent').attr('role','presentation').append(submenu);$(this).parent().parent().addClass('xcc-wrapper');$(this).html($(this).data('not')).addClass('out');var ele=document.querySelector('.load-app');if(ele){if(typeof angular!=='undefined'&&!angular.element(ele).scope()&&!angular.element(ele).injector()){angular.bootstrap(ele,["st.apply.site"]);}}});var count=0;$('.xcc-profile-builder').each(function(){var loggedOutMessage=_XC_CONFIG.signInHTML;if(_XCC_PW_CONFIG.logged_out_message===""){$(this).html(loggedOutMessage);}});$('.xcc-angular-app-load').each(function(){var newId="xcc-angular-app-load-"+count;var activityContent='<div id="'+newId+'" ng-app="st.apply.site" ng-controller="mainController as mc">';if(_XCC_CA_CONFIG.not_logged_in==='custom'){activityContent+=_XCC_CA_CONFIG.not_logged_in_cust_html}else{activityContent+=_XC_CONFIG.signInHTML;}
activityContent+=' <div candidate-activity-notification-widget></div></div>';$(this).html(activityContent);if(typeof angular!=='undefined'){angular.element('#'+newId).scope();}
count++;});}
else if(xcc!==null&&xcc.isLocked!==true){try{$('.xcc-logged-out').hide();$('.xcc-logged-in,.xcc-sign-in').each(function(){if($(this).data('if')===''){$(this).html(parse_string($(this).html())).show();}
else{if($(this).is('.xcc-sign-in')&&!xcc.hasOwnProperty('from_chat')){var shortcode_settings=$(this).data();$('.menu-inline .xcc-sign-in').show();if(typeof shortcode_settings_init==="undefined"||shortcode_settings_init==={}){shortcode_settings_init=$(this).data();}
shortcode_settings.if=parse_string(shortcode_settings_init.if);var submenu='<div class="xcc-sign-in-submenu" id="sign-in-submenu" aria-hidden="true">';submenu+='<a class="account-link" href="/'+(_XC_CONFIG.lang?_XC_CONFIG.lang+'/':'')+'profile/">'+XCLOUD.i18n(shortcode_settings.profile,'labels')+'</a>';shortcode_settings.logout=parse_string(shortcode_settings_init.logout);submenu+='<a class="xcc-log-out" onclick="XCLOUD.log_out(false, event)" href="#">'+XCLOUD.i18n(shortcode_settings.logout,'labels')+'</a>';submenu+='</div>';$('.xcc-sign-in').attr('aria-label',shortcode_settings.if);$(this).parent().addClass('xcc-sign-in-parent').append(submenu);$(this).html(parse_string($(this).data('if'))).addClass('in');$(this).parent().parent().addClass('xcc-wrapper');}
else{if(xcc.hasOwnProperty($(this).data('if'))){$(this).html(parse_string(XCLOUD.i18n($(this).html()))).show();}
else{$(this).siblings('.xcc-logged-out').show();}}}});$('.xcc-angular-app-load').each(function(){if(location.pathname.indexOf("/profile/")===-1&&location.pathname.indexOf("/apply/")===-1){var activityContent='<div ng-app="st.apply.site" ng-controller="mainController as mc"><div candidate-activity-notification-widget></div></div>';$(this).html(activityContent);}});}
catch(x){CWS.log(x);}}
if(typeof CWS!=='undefined'){if(typeof loadRecommendationWidgets!=='undefined'&&jQuery.isFunction(loadRecommendationWidgets)){loadRecommendationWidgets(XCLOUDInitiLoad);XCLOUDInitiLoad=false;}}
XCLOUD.load_persona_data(xcc);},logged_in:function(){return!(get_candidate()===null);},parse:parse_string,get:getter};})(jQuery);XCLOUD.load_persona_data=function(user){var $=jQuery;var widgets=$('.xcc-persona-widget');if(!widgets.length){return;}
function build_widget(el,data,options){var html='<h3 class="widgettitle">'+options.title+'</h3>';if(data.length>0){for(var i=0,len=data.length;i<len;i++){html=XCLOUD.apply_filter('persona_widget_pre_item',html,data[i]);var title=data[i].title.rendered;html+='<h4 class="av-magazine-title entry-title" itemprop="headline"><a href="'+data[i].link+'" title="Link to: '+title+'">'+title+'</a></h4>';html+='<hr />';html=XCLOUD.apply_filter('persona_widget_post_item',html,data[i]);}
el.html(html);}}
widgets.each(function(){var el=$(this);var data=decodeURIComponent($(this).data('options'));data=JSON.parse(data);data=XCLOUD.apply_filter('persona_widget_options',data);if(user===null&&!data.not_logged_in){return;}
var post_type=data.post_types.split(',');var requests=[];var persona_data=[];for(var i=0,len=post_type.length;i<len;i++){var url='/wp-json/wp/v2/'+post_type[i];if(user!==null&&user.areaInterest){url+='?filter[taxonomy]=persona&filter[term]='+encodeURIComponent(user.areaInterest);}
else{url+='?persona='+data.not_logged_in;}
requests.push($.get(url,function(results){if(DEBUG){console.log(results);}
persona_data=_.union(persona_data,results);}));}
$.when.apply(undefined,requests).then(function(results){persona_data=XCLOUD.apply_filter('persona_widget_data',persona_data);build_widget(el,persona_data,data);});});};XCLOUD.log_out=function(no_reload,event,isRedirectionForHomePage,skipRedirection){var key='candidate';var languageCode='';var bearerToken='';if(event){event.preventDefault();event.stopPropagation();}
if(_XC_CONFIG.lang&&_XC_CONFIG.lang!=='en'){languageCode='/'+_XC_CONFIG.lang;}
if(_XC_CONFIG.bearer_polling)
{window.clearInterval(_XC_CONFIG.bearer_polling);}
if(ATS_URL&&ATS_INSTANCE){if(_XC_CONFIG.org){if(localStorage&&localStorage.getItem(_XC_CONFIG.org+'.bearerToken')){bearerToken="bearer "+JSON.parse(JSON.parse(localStorage.getItem(_XC_CONFIG.org+'.bearerToken')).data).token;if(bearerToken){jQuery.ajax({url:ATS_URL+ATS_INSTANCE+'/rest/logout',headers:{"Authorization":bearerToken}});}}}}
XCLOUD.local.remove(_XC_CONFIG.org+'.'+'bearerToken');XCLOUD.local.remove(_XC_CONFIG.org+'.'+'username');XCLOUD.removeLocalSession(key);if(_XC_CONFIG.org+'.'+'applicationURL'!=null){XCLOUD.local.remove(_XC_CONFIG.org+'.'+'applicationURL');}
XCLOUD.cookies.removeItem('xcc');window.sessionStorage.removeItem("ApplyResumeStateContainer");window.sessionStorage.removeItem("SocialSiteStateContainer");window.sessionStorage.removeItem("hiddenFieldGroups");window.sessionStorage.removeItem("attachmentContainer");if((_XC_CONFIG.auth0["sso_enable"]&&typeof auth0!=='undefined')||(XCLOUD.cookies.getItem('is_sponsor')&&SFX&&SFX.referrals&&_XC_CONFIG.auth0['domain']&&_XC_CONFIG.auth0['clientID'])){const REDIRECT_URL=window.location.origin+'/auth0_logout';if(XCLOUD.cookies.getItem('is_sponsor')&&SFX&&SFX.referrals)
{SFX.referrals.logout();}
var cweb=cognito.webAuth({domain:_XC_CONFIG.auth0['domain'],redirectUri:REDIRECT_URL,clientID:_XC_CONFIG.auth0['clientID'],responseType:'token id_token',});cweb.logout({returnTo:window.location.origin+'/auth0_logout/'});return;}
else if((skipRedirection&&skipRedirection===true)){return;}
if(XCLOUD.cookies.getItem('is_sponsor')&&SFX&&SFX.referrals){SFX.referrals.logout();return;}
if(_XC_CONFIG.menuShortcodesAttr!==undefined&&_XC_CONFIG.menuShortcodesAttr!==null){if(isRedirectionForHomePage===true){window.location=languageCode+'/';}else{if(_XC_CONFIG.menuShortcodesAttr.logoutdest!==undefined&&_XC_CONFIG.menuShortcodesAttr.logoutdest!=='#'&&_XC_CONFIG.menuShortcodesAttr.logoutdest!==null){window.location.href=_XC_CONFIG.menuShortcodesAttr.logoutdest;}else if(no_reload!==true){if(_XC_CONFIG.login_modal.disabled===true){window.location.reload();}else{window.location=languageCode+'/';}}}}else if(isRedirectionForHomePage!==false&&(!isRedirectionForHomePage||isRedirectionForHomePage===true)){window.location=languageCode+'/';}
else if(no_reload!==true){window.location.reload();}};XCLOUD.removeLocalSession=function(key){XCLOUD.local.remove(_XC_CONFIG.org+'.'+key);XCLOUD.local.remove(key,true);XCLOUD.local.remove(_XC_CONFIG.org+'.'+'credentials');XCLOUD.local.remove(_XC_CONFIG.org+'.'+'oauthcredentials');if(_XC_CONFIG.auth0["sso_enable"]){XCLOUD.local.remove(_XC_CONFIG.org+'.'+'auth0Credentials');}
XCLOUD.local.remove(_XC_CONFIG.org+'.'+'roles');XCLOUD.local.remove(_XC_CONFIG.org+'.'+'remember_me');XCLOUD.local.remove(_XC_CONFIG.org+'.'+'Y9dN0');XCLOUD.local.remove(_XC_CONFIG.org+'.'+'Y9dI0');XCLOUD.local.remove(_XC_CONFIG.org+'.'+'applyCandidate');if(_XC_CONFIG.org+'.'+'isWorkFlowTriggered'){XCLOUD.local.remove(_XC_CONFIG.org+'.'+'isWorkFlowTriggered');}}
XCLOUD.change_iframe_height=function(){try{var iframes=document.getElementsByClassName('dynamic-iframe');if(iframes.length>0){for(var i=0,len=iframes.length;i<len;i++){if(iframes[i].contentWindow&&iframes[i].contentWindow.document){iframes[i].height="";jQuery(iframes[i]).css('height',iframes[i].contentWindow.document.body.scrollHeight+"px");}}}}
catch(x){}};XCLOUD.view_loaded=function(e){if(DEBUG){if(window.location.pathname.indexOf("/profile/thank-you/")!=-1||window.location.pathname.indexOf("campaign")!=-1)
window.scrollTo(0,0);console.log('View loaded event emitted');}
if(XCLOUD.in_iframe()&&parent.XCLOUD){parent.XCLOUD.change_iframe_height();}
XCLOUD.refresh_language_switcher();XCLOUD.apply_filter('xcc_view_loaded',{});};XCLOUD.toggleSubmenu=function(expand){if(expand){$('.xcc-sign-in').attr('aria-expanded','true');$('.xcc-sign-in-submenu').attr('aria-hidden','false').show();}else{$('.xcc-sign-in').attr('aria-expanded','false');$('.xcc-sign-in-submenu').attr('aria-hidden','true').hide();}};XCLOUD.filters={};XCLOUD.add_filter=function(filter_name,filter_function){if(typeof filter_function=='function'){if(!XCLOUD.filters.hasOwnProperty(filter_name)){XCLOUD.filters[filter_name]=[];}
XCLOUD.filters[filter_name].push(filter_function);}};XCLOUD.apply_filter=function(filter_name,obj){if(XCLOUD.filters.hasOwnProperty(filter_name)){for(var i=0,len=XCLOUD.filters[filter_name].length;i<len;i++){obj=XCLOUD.filters[filter_name][i].apply(this,Array.prototype.slice.call(arguments,1));}}
return obj;};XCLOUD.i18n=function(str,context){if(_XC_CONFIG.lang===null||_XC_CONFIG.lang==='en'||typeof _XC_i18n=="undefined"||!_XC_i18n){return str;}
if(_XC_i18n[context]&&_XC_i18n[context][str]&&_XC_i18n[context][str][_XC_CONFIG.lang]){return _XC_i18n[context][str][_XC_CONFIG.lang];}
return str;};XCLOUD.in_iframe=function(){try{return window.self!==window.top;}catch(e){return true;}};var last_body_height;XCLOUD.refresh_language_switcher=function(){if(_XC_CONFIG.lang){var app_page=location.pathname.replace('/'+_XC_CONFIG.lang+'/','/');if(app_page.indexOf('/profile')!==0&&app_page.indexOf('/apply')!==0){return;}
jQuery('.wpml-ls-menu-item a').each(function(){var l=document.createElement("a");l.href=this.href;var path=l.pathname;var lang_code=RegExp('^/(.+?)/').exec(path);if(lang_code!==null){if(lang_code[1]in _XC_CONFIG.langs){this.href='/'+lang_code[1]+app_page+location.search;}
else{this.href=app_page+location.search;}}});}};XCLOUD.syncUiSelectAccessibilityRoles=function(){$('.ui-select-match').each(function(){const $selectMatch=$(this);const $selectedItems=$selectMatch.find('span[ng-repeat*="$item in $select.selected"]:visible');const $label=$selectMatch.closest('.form-group').siblings('label.control-label:visible').first();if($selectedItems.length>0){let labelText='';if($label.length){labelText=$label.clone().children().remove().end().text().trim();}
const ariaLabel=labelText?`Selected ${labelText}`:'Selected items';$selectMatch.attr('role','list');$selectMatch.attr('aria-label',ariaLabel);$selectedItems.each(function(){$(this).attr('role','listitem');});}else{$selectMatch.removeAttr('role aria-label');}});XCLOUD.multiSelectlabels();};XCLOUD.multiSelectlabels=function(){$('.ui-select-container').each(function(index){const $label=$(this).closest('.form-group').siblings('label.control-label:visible');if($label.length&&!$(this).find('.ui-select-search').attr('aria-labelledby')){const labelText=$label.clone().children().remove().end().text().trim();if(labelText){$(this).find('.ui-select-search').attr('aria-label',labelText);}}});};(function($){$(document).ready(function(){shortcode_settings_init=$('.xcc-sign-in').data();var formEle=document.querySelector('.load-form');if(formEle&&typeof angular!=='undefined'){angular.bootstrap(formEle,["st.apply.site"]);}
XCLOUD.personalize.init();if(XCLOUD.in_iframe()&&parent.XCLOUD){last_body_height=$('body').outerHeight();parent.XCLOUD.change_iframe_height();setInterval(function(){var new_body_height=$('body').outerHeight();if(new_body_height!==last_body_height){parent.XCLOUD.change_iframe_height();last_body_height=new_body_height;}},100);}
$('body').delegate('.xcc-log-out','click',function(e){XCLOUD.log_out(false,e);});$('.xcc-sign-in').click(function(e){e.preventDefault();e.stopPropagation();return false;});var scrollToTop=jQuery('#scroll-top-link');if(scrollToTop.length>0){scrollToTop.click(function(e){e.preventDefault();window.scrollTo(0,0);});}
if(window.matchMedia("(max-width:767px)").matches||navigator.userAgent.match(/iPad/i)!=null){$('.menu-dropdown .xcc-sign-in').click(function(){$('.xcc-sign-in-submenu').toggle();});}
let lastFocusedElement=null;$(document).on('click focus','.ui-select-search',function(event){if(document.activeElement){lastFocusedElement=document.activeElement;}});$(document).on('click','.ui-select-match-close',function(event){var nextElement=$('.ui-select-search');if(lastFocusedElement){nextElement=lastFocusedElement;}
var closeElements=Array.from($(event.target).parents('.ui-select-match').find('.ui-select-match-close'));if(closeElements.length<=0){nextElement.focus();}});$(document).on('keydown','.ui-select-match-close',function(event){if(event.type==='keydown'&&event.key!=='Enter'){return;}else{var nextElement=$(event.target).parents('.ui-select-match').siblings('input');var closeElements=Array.from($(event.target).parents('.ui-select-match').find('.ui-select-match-close'));const currentIndex=closeElements.indexOf(event.target);if(currentIndex>=0&&currentIndex<closeElements.length-1){nextElement=closeElements[currentIndex];}
event.preventDefault();event.target.click();nextElement.focus();}});$(document).on('click','.ui-select-match-close, .ui-select-choices-row',function(){XCLOUD.syncUiSelectAccessibilityRoles();});$(document).on('keyup','.ui-select-choices-row, .ui-select-search',function(event){const key=event.key;if(key==='Enter'||key===' '){XCLOUD.syncUiSelectAccessibilityRoles();}});$(document).on('change','.schema-form-select select',function(){XCLOUD.multiSelectlabels();});$('.xcc-sign-in').on('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();var isExpanded=$('.xcc-sign-in').attr('aria-expanded')==='true';XCLOUD.toggleSubmenu(!isExpanded);}
if(e.key==='Escape'){XCLOUD.toggleSubmenu(false);}});$('.xcc-sign-in').on('click',function(){var isExpanded=$(this).attr('aria-expanded')==='true';XCLOUD.toggleSubmenu(!isExpanded);});jQuery('body').append('<span id="form-update-aria-live" class="visually-hidden sr-only" aria-live="polite" aria-atomic="true"></span>');XCLOUD.add_filter('XCC_LAST_FORM_SUBMIT',informCandidateAboutFormStatus);function informCandidateAboutFormStatus(){jQuery('#form-update-aria-live').text(XCLOUD.i18n("Your information is being updated.","text"));}});})(jQuery);